"""add scoring weights table

Revision ID: 340264729e5d
Revises: 043b55cb56e3
Create Date: 2026-07-09 21:35:32.942792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340264729e5d'
down_revision: Union[str, Sequence[str], None] = '043b55cb56e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor')
    )
    op.create_index(op.f('ix_scoring_weights_id'), 'scoring_weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_weights_id'), table_name='scoring_weights')
    op.drop_table('scoring_weights')
    # ### end Alembic commands ###
